// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeleteUserProfile(ctx context.Context, userID uuid.UUID) error
	EmailExists(ctx context.Context, email string) (EmailExistsRow, error)
	// =========================================
	// USER PROFILES
	// =========================================
	GetAllUserProfiles(ctx context.Context) ([]UserProfile, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserProfileByID(ctx context.Context, id uuid.UUID) (UserProfile, error)
	GetUserProfileByUserID(ctx context.Context, userID uuid.UUID) (UserProfile, error)
	GetUserWithProfile(ctx context.Context, id uuid.UUID) (GetUserWithProfileRow, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
