// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    role,
    status
)
VALUES ($1, $2, $3, $4)
    RETURNING
    id,
    email,
    role,
    status,
    password_hash,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	Status       string `json:"status"`
}

type CreateUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	PasswordHash    string             `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT id,email,role
FROM users
WHERE email =  $1
`

type EmailExistsRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Role  string    `json:"role"`
}

func (q *Queries) EmailExists(ctx context.Context, email string) (EmailExistsRow, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var i EmailExistsRow
	err := row.Scan(&i.ID, &i.Email, &i.Role)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    password_hash,
    role,
    status,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    role,
    status,
    password_hash,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE id = $1
ORDER BY created_at DESC, id DESC
`

type GetUserByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	PasswordHash    string             `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithProfile = `-- name: GetUserWithProfile :one
SELECT
    u.id,
    u.email,
    u.role,
    u.status,
    u.created_at,

    p.first_name,
    p.last_name,
    p.display_name,
    p.avatar_url
FROM users u
         LEFT JOIN user_profiles p
                   ON p.user_id = u.id
WHERE u.id = $1
  AND u.deleted_at IS NULL
`

type GetUserWithProfileRow struct {
	ID          uuid.UUID   `json:"id"`
	Email       string      `json:"email"`
	Role        string      `json:"role"`
	Status      string      `json:"status"`
	CreatedAt   time.Time   `json:"created_at"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   string      `json:"avatar_url"`
}

func (q *Queries) GetUserWithProfile(ctx context.Context, id uuid.UUID) (GetUserWithProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserWithProfile, id)
	var i GetUserWithProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    id,
    email,
    role,
    status,
    password_hash,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUsersRow struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	PasswordHash    string             `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.PasswordHash,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
