// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
    user_id,
    first_name,
    last_name,
    display_name,
    phone,
    avatar_url,
    bio,
    date_of_birth,
    gender,
    country,
    city,
    address
)
VALUES (
           $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
       )
    RETURNING
    id,
    user_id,
    first_name,
    last_name,
    display_name,
    phone,
    avatar_url,
    bio,
    date_of_birth,
    gender,
    country,
    city,
    address,
    created_at,
    updated_at
`

type CreateUserProfileParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	DisplayName string      `json:"display_name"`
	Phone       pgtype.Text `json:"phone"`
	AvatarUrl   string      `json:"avatar_url"`
	Bio         string      `json:"bio"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Gender      pgtype.Text `json:"gender"`
	Country     pgtype.Text `json:"country"`
	City        pgtype.Text `json:"city"`
	Address     string      `json:"address"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Phone,
		arg.AvatarUrl,
		arg.Bio,
		arg.DateOfBirth,
		arg.Gender,
		arg.Country,
		arg.City,
		arg.Address,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.Gender,
		&i.Country,
		&i.City,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserProfile = `-- name: DeleteUserProfile :exec
DELETE FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) DeleteUserProfile(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserProfile, userID)
	return err
}

const getAllUserProfiles = `-- name: GetAllUserProfiles :many

SELECT
    id,
    user_id,
    first_name,
    last_name,
    display_name,
    phone,
    avatar_url,
    bio,
    date_of_birth,
    gender,
    country,
    city,
    address,
    created_at,
    updated_at
FROM user_profiles
ORDER BY created_at DESC, id DESC
`

// =========================================
// USER PROFILES
// =========================================
func (q *Queries) GetAllUserProfiles(ctx context.Context) ([]UserProfile, error) {
	rows, err := q.db.Query(ctx, getAllUserProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserProfile{}
	for rows.Next() {
		var i UserProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Phone,
			&i.AvatarUrl,
			&i.Bio,
			&i.DateOfBirth,
			&i.Gender,
			&i.Country,
			&i.City,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT
    id,
    user_id,
    first_name,
    last_name,
    display_name,
    phone,
    avatar_url,
    bio,
    date_of_birth,
    gender,
    country,
    city,
    address,
    created_at,
    updated_at
FROM user_profiles
WHERE id = $1
`

func (q *Queries) GetUserProfileByID(ctx context.Context, id uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByID, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.Gender,
		&i.Country,
		&i.City,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT
    id,
    user_id,
    first_name,
    last_name,
    display_name,
    phone,
    avatar_url,
    bio,
    date_of_birth,
    gender,
    country,
    city,
    address,
    created_at,
    updated_at
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.Gender,
		&i.Country,
		&i.City,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles
SET
    first_name = $2,
    last_name = $3,
    display_name = $4,
    phone = $5,
    avatar_url = $6,
    bio = $7,
    date_of_birth = $8,
    gender = $9,
    country = $10,
    city = $11,
    address = $12,
    updated_at = NOW()
WHERE user_id = $1
    RETURNING
    id,
    user_id,
    first_name,
    last_name,
    display_name,
    phone,
    avatar_url,
    bio,
    date_of_birth,
    gender,
    country,
    city,
    address,
    created_at,
    updated_at
`

type UpdateUserProfileParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	DisplayName string      `json:"display_name"`
	Phone       pgtype.Text `json:"phone"`
	AvatarUrl   string      `json:"avatar_url"`
	Bio         string      `json:"bio"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Gender      pgtype.Text `json:"gender"`
	Country     pgtype.Text `json:"country"`
	City        pgtype.Text `json:"city"`
	Address     string      `json:"address"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Phone,
		arg.AvatarUrl,
		arg.Bio,
		arg.DateOfBirth,
		arg.Gender,
		arg.Country,
		arg.City,
		arg.Address,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Bio,
		&i.DateOfBirth,
		&i.Gender,
		&i.Country,
		&i.City,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
